from sqlalchemy import Column,Text,Integer
from db.base_class import Base
class Usuario(Base):

    usu_id            = Column(Integer,primary_key=True)
    usu_nombre        = Column(Text)
    usu_apellido      = Column(Text)
    usu_genero        = Column(Text)
    usu_pais          = Column(Text)
    usu_edad          = Column(Text)
    usu_provincia     = Column(Text)
    usu_canton        = Column(Text)
    usu_parroquia     = Column(Text)
    usu_street1       = Column(Text)
    usu_street2       = Column(Text)
    usu_phone         = Column(Text)
    usu_phonehome     = Column(Text)
    usu_numhome       = Column(Text)
    usu_email         = Column(Text)
    usu_password      = Column(Text)
 

""" 


 { 
  "":"Gabriel",
  "":"Morales",
  "":"Hombre",
  "":"Ecuador",
  "":"25",
  "":"Pichincha",
  "":"Quito",
  "":"Solanda",
  "":"Av teniente hugo ortiz",
  "":"juan nuñez",
  "":"0978775042",
  "":"022680251",
  "":"S23-08",
  "":"gabrielmorales201264@gmail.com",
  "":"gabriel2012@M"}

  CREATE TABLE usuario (

    usu_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    usu_nombre TEXT,
    usu_apellido TEXT,
    usu_genero TEXT,
    usu_pais TEXT,
    usu_edad TEXT,
    usu_provincia TEXT,
    usu_canton TEXT,
    usu_parroquia TEXT,
    usu_street1 TEXT,
    usu_street2 TEXT,
    usu_phone TEXT,
    usu_phonehome TEXT,
    usu_numhome TEXT,
    usu_email TEXT,
    usu_password TEXT
);  
   """
  
  
  
  
  
  
  
  
 
 
   